version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/server
file_exists_behavior: OVERWRITE

hooks:
  AfterInstall:
    - location: scripts/stop_container.sh
      timeout: 300

  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 300

